# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];

	boot = {
		initrd.availableKernelModules = [
			"uhci_hcd" "ehci_pci" "ata_piix" "megaraid_sas" "usbhid" "usb_storage" "sd_mod" "sr_mod"
		];
		initrd.kernelModules = [ ];
		kernelModules = [ "kvm-intel" ];
		extraModulePackages = [ ];
	};

	fileSystems = {
		"/" = {
			device = "/dev/disk/by-uuid/c2e76eee-7609-4690-b338-0582b75a0698";
			fsType = "ext4";
		};
		"/boot" = {
			device = "/dev/disk/by-uuid/9c77768e-37c9-4e57-8459-1ffc964ad9e4";
			fsType = "ext4";
		};
	};
	swapDevices = [ ];

	hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
	powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
